---
title: PG Courses/Colleges-KERALA
author: ''
date: '2018-12-14'
slug: pg-courses-colleges
categories: []
tags: []
---
**MSc STATISTICS**

* [Department of Statistics - University of Calicut
](https://statistics.uoc.ac.in/)


* [Govt. Arts & Science College,Kozhikode](http://www.gasckkd.ac.in/statistics/)

* [St.Thomas College (Autonomous), Thrissur](http://stthomas.ac.in/department_info?department=Statistics)


* [Government Victoria College Palakkad](http://www.victoriacollege.in/index.php)

* [Farook College(Autonomous),Kozhikode](https://www.farookcollege.ac.in/department-of-statistics/)

**MSc STATISTICS**(Self Financing)

* [WMO Arts & Science College MUTTIL WAYANAD](https://wmocollege.ac.in/pg.html)


**M.Sc. : Big Data Analytics(Self Financing)**


* [St. Joseph's College, Devagiri(Autonomous)](http://www.sjc.ac.in/courses.html#)


**M.Sc Agricultural Statistics-3 yrs**
You must have a bachelor degree in Agriculture or equivalent recognized by KAU with an OGPA of 6.50/10.00 for General Category candidates and 6.00/10.00 for SC/ST. If you have a bachelor degree in B. Sc. Mathematics/Statistics with 50% marks from a recognised University can also apply

* [College of Agriculture, Vellayani](http://www.kau.in/institution/college-agriculture-vellayani)

* [College of Horticulture, Vellanikkara](http://www.kau.in/institution/college-horticulture-vellanikkara)




